### ISSUE TITLE
`OptimizationPRIMA` errors with `AutoForwardDiff`

### ISSUE THREAD

**Issue by soldasim** [soldasim/BOSS.jl#28]
Created an issue at Optimization.jl: https://github.com/SciML/Optimization.jl/issues/719

For all the unconstrained algorithms, pass keyword `autodiff = nothing` to `OptimizationAM` and `OptimizationMLE` as a workaround.

COBYLA is probably just broken until this is resolved. (Unless other AD backends work. (?))

**Comment by zaikunzhang** [comment]
Hi @soldasim ,

Thank you for using PRILA. Has the issue been resolved? See 

https://github.com/libprima/PRIMA.jl/issues/27

Best regards,
Zaikun

**Comment by soldasim** [comment]
Hi @zaikunzhang ,

yes, the issue is resolved by the resolution of https://github.com/SciML/Optimization.jl/issues/719. :)

Thanks!
